# Generated by Django 5.1.5 on 2025-02-04 18:40

import accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_twilio_auth_token_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='twilio_auth_token',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='twilio_sid',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='whatsapp_business_number',
        ),
        migrations.AlterField(
            model_name='profile',
            name='twilio_phone_number',
            field=models.CharField(blank=True, max_length=15, validators=[accounts.validators.validate_international_phone_number]),
        ),
    ]
