# Generated by Django 5.1.5 on 2025-02-05 05:58

import accounts.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_profile_twilio_auth_token_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=20, unique=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('customer_phone_number', models.CharField(max_length=15, validators=[accounts.validators.validate_international_phone_number])),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('READY', 'Ready')], default='PENDING', max_length=10)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile')),
            ],
        ),
    ]
