# Generated by Django 5.1.5 on 2025-02-05 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderNumberTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_order_number', models.IntegerField(default=50)),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.IntegerField(unique=True),
        ),
    ]
